import {
  tablerBaselineDensityMedium,
  tablerBorderCorners,
  tablerBorderRadius,
  tablerBrandGithub,
  tablerBuildingStore,
  tablerChartAreaLine,
  tablerCheck,
  tablerChevronDown,
  tablerCode,
  tablerCoffee,
  tablerComponents,
  tablerDatabase,
  tablerFileText,
  tablerLayoutDashboard,
  tablerPalette,
  tablerSearch,
  tablerSettings,
  tablerShadow,
  tablerShieldLock,
  tablerSunMoon,
  tablerTools,
} from '@ng-icons/tabler-icons';

export const DOCS_HEADER_ICONS = {
  tablerBaselineDensityMedium,
  tablerBorderCorners,
  tablerBorderRadius,
  tablerBrandGithub,
  tablerBuildingStore,
  tablerCheck,
  tablerChevronDown,
  tablerCode,
  tablerCoffee,
  tablerComponents,
  tablerChartAreaLine,
  tablerDatabase,
  tablerFileText,
  tablerLayoutDashboard,
  tablerPalette,
  tablerSearch,
  tablerSettings,
  tablerShadow,
  tablerShieldLock,
  tablerSunMoon,
  tablerTools,
};
