import { NgModule } from '@angular/core';
import {
  FrCombobox,
  FrComboboxChip,
  FrComboboxChipRemove,
  FrComboboxChips,
  FrComboboxChipsInput,
  FrComboboxClear,
  FrComboboxCollection,
  FrComboboxContent,
  FrComboboxEmpty,
  FrComboboxError,
  FrComboboxGroup,
  FrComboboxInput,
  FrComboboxItem,
  FrComboboxItemIndicator,
  FrComboboxLabel,
  FrComboboxList,
  FrComboboxPanel,
  FrComboboxSeparator,
  FrComboboxTrigger,
  FrComboboxValueList,
} from './src/combobox';

@NgModule({
  imports: [
    FrCombobox,
    FrComboboxChip,
    FrComboboxChipRemove,
    FrComboboxChips,
    FrComboboxChipsInput,
    FrComboboxClear,
    FrComboboxCollection,
    FrComboboxContent,
    FrComboboxEmpty,
    FrComboboxError,
    FrComboboxGroup,
    FrComboboxInput,
    FrComboboxItem,
    FrComboboxItemIndicator,
    FrComboboxLabel,
    FrComboboxList,
    FrComboboxPanel,
    FrComboboxSeparator,
    FrComboboxTrigger,
    FrComboboxValueList,
  ],
  exports: [
    FrCombobox,
    FrComboboxChip,
    FrComboboxChipRemove,
    FrComboboxChips,
    FrComboboxChipsInput,
    FrComboboxClear,
    FrComboboxCollection,
    FrComboboxContent,
    FrComboboxEmpty,
    FrComboboxError,
    FrComboboxGroup,
    FrComboboxInput,
    FrComboboxItem,
    FrComboboxItemIndicator,
    FrComboboxLabel,
    FrComboboxList,
    FrComboboxPanel,
    FrComboboxSeparator,
    FrComboboxTrigger,
    FrComboboxValueList,
  ],
})
export class FrComboboxModule {}
