import { NgModule } from '@angular/core';
import {
  FrSidebar,
  FrSidebarContent,
  FrSidebarFooter,
  FrSidebarGroup,
  FrSidebarGroupAction,
  FrSidebarGroupContent,
  FrSidebarGroupLabel,
  FrSidebarHeader,
  FrSidebarInset,
  FrSidebarMenu,
  FrSidebarMenuAction,
  FrSidebarMenuBadge,
  FrSidebarMenuButton,
  FrSidebarMenuItem,
  FrSidebarMenuSkeleton,
  FrSidebarMenuSub,
  FrSidebarMenuSubButton,
  FrSidebarMenuSubItem,
  FrSidebarProvider,
  FrSidebarRail,
  FrSidebarTrigger,
} from './src/sidebar';

@NgModule({
  imports: [
    FrSidebar,
    FrSidebarContent,
    FrSidebarFooter,
    FrSidebarGroup,
    FrSidebarGroupAction,
    FrSidebarGroupContent,
    FrSidebarGroupLabel,
    FrSidebarHeader,
    FrSidebarInset,
    FrSidebarMenu,
    FrSidebarMenuAction,
    FrSidebarMenuBadge,
    FrSidebarMenuButton,
    FrSidebarMenuItem,
    FrSidebarMenuSkeleton,
    FrSidebarMenuSub,
    FrSidebarMenuSubButton,
    FrSidebarMenuSubItem,
    FrSidebarProvider,
    FrSidebarRail,
    FrSidebarTrigger,
  ],
  exports: [
    FrSidebar,
    FrSidebarContent,
    FrSidebarFooter,
    FrSidebarGroup,
    FrSidebarGroupAction,
    FrSidebarGroupContent,
    FrSidebarGroupLabel,
    FrSidebarHeader,
    FrSidebarInset,
    FrSidebarMenu,
    FrSidebarMenuAction,
    FrSidebarMenuBadge,
    FrSidebarMenuButton,
    FrSidebarMenuItem,
    FrSidebarMenuSkeleton,
    FrSidebarMenuSub,
    FrSidebarMenuSubButton,
    FrSidebarMenuSubItem,
    FrSidebarProvider,
    FrSidebarRail,
    FrSidebarTrigger,
  ],
})
export class FrSidebarModule {}
