import { NgModule } from '@angular/core';
import {
  FrMenuBar,
  FrMenuBarCheckboxItem,
  FrMenuBarContent,
  FrMenuBarItem,
  FrMenuBarItemIndicator,
  FrMenuBarLabel,
  FrMenuBarMenu,
  FrMenuBarPanel,
  FrMenuBarRadioGroup,
  FrMenuBarRadioItem,
  FrMenuBarSeparator,
  FrMenuBarShortcut,
  FrMenuBarSub,
  FrMenuBarSubTrigger,
  FrMenuBarTrigger,
} from './src/menubar';

@NgModule({
  imports: [
    FrMenuBar,
    FrMenuBarCheckboxItem,
    FrMenuBarContent,
    FrMenuBarItem,
    FrMenuBarItemIndicator,
    FrMenuBarLabel,
    FrMenuBarMenu,
    FrMenuBarPanel,
    FrMenuBarRadioGroup,
    FrMenuBarRadioItem,
    FrMenuBarSeparator,
    FrMenuBarShortcut,
    FrMenuBarSub,
    FrMenuBarSubTrigger,
    FrMenuBarTrigger,
  ],
  exports: [
    FrMenuBar,
    FrMenuBarCheckboxItem,
    FrMenuBarContent,
    FrMenuBarItem,
    FrMenuBarItemIndicator,
    FrMenuBarLabel,
    FrMenuBarMenu,
    FrMenuBarPanel,
    FrMenuBarRadioGroup,
    FrMenuBarRadioItem,
    FrMenuBarSeparator,
    FrMenuBarShortcut,
    FrMenuBarSub,
    FrMenuBarSubTrigger,
    FrMenuBarTrigger,
  ],
})
export class FrMenubarModule {}
